<?php

$nav = [
    ['label' => 'Inicio', 'link' => Config::getData('url') . '/home', 'icon' => 'dashboard', 'dropdown' => false],
    ['label' => 'Administração', 'link' => '#', 'icon' => 'gears', 'dropdown' => [
            ['label' => Config::getData('titlePagesAliases', 'Modulo'), 'link' => Config::getData('url') . '/Modulo', 'icon' => 'angle-right', 'dropdown' => false],
            ['label' => Config::getData('titlePagesAliases', 'Curso'), 'link' => Config::getData('url') . '/Curso', 'icon' => 'angle-right', 'dropdown' => false],
            ['label' => Config::getData('titlePagesAliases', 'Polo'), 'link' => Config::getData('url') . '/Polo', 'icon' => 'angle-right', 'dropdown' => false],
            ['label' => Config::getData('titlePagesAliases', 'Pessoas'), 'link' => Config::getData('url') . '/Usuario', 'icon' => 'angle-right', 'dropdown' => false],
            ['label' => Config::getData('titlePagesAliases', 'Cadastros'), 'link' => '#', 'icon' => 'list', 'dropdown' => [
                    ['label' => 'Indisponibilidade', 'link' => Config::getData('url') . '/indisp', 'icon' => 'angle-right', 'dropdown' => false],
                    ['label' => Config::getData('titlePagesAliases', 'ReembolsoMotivo'), 'link' => Config::getData('url') . '/ReembolsoMotivo', 'icon' => 'angle-right', 'dropdown' => false],
                    ['label' => Config::getData('titlePagesAliases', 'conta'), 'link' => Config::getData('url') . '/Conta', 'icon' => 'angle-right', 'dropdown' => false],
                    ['label' => 'Permissões de usuários', 'link' => Config::getData('url') . '/Usuario/0/1', 'icon' => 'angle-right', 'dropdown' => false],
                ]],
//            ['label' => Config::getData('titlePagesAliases', 'Pessoas'), 'link' => Config::getData('url') . '/Usuario', 'icon' => 'angle-right', 'dropdown' => [
//                    //['label' => 'Perfil de permissões', 'link' => Config::getData('url') . '/Usuario/0/1', 'icon' => 'angle-right', 'dropdown' => false],
//                    ['label' => Config::getData('titlePagesAliases', 'Professores'), 'link' => Config::getData('url') . '/Usuario/0/15', 'icon' => 'angle-right', 'dropdown' => false],
//                    //['label' => Config::getData('titlePagesAliases', 'Alunos'), 'link' => Config::getData('url') . '/Usuario/0/16', 'icon' => 'angle-right', 'dropdown' => false],
//                    ['label' => Config::getData('titlePagesAliases', 'Todos'), 'link' => Config::getData('url') . '/Usuario', 'icon' => 'angle-right', 'dropdown' => false],
//                ]],
        ]],
    ['label' => 'Secretaria', 'link' => '#', 'icon' => 'money', 'dropdown' => [
            ['label' => 'Formulário de inscrição', 'link' => Config::getData('url') . '/inscricao', 'icon' => 'angle-right', 'dropdown' => false],
            ['label' => 'Gestão de matriculas', 'link' => Config::getData('url') . '/Matricula', 'icon' => 'angle-right', 'dropdown' => false],
            ['label' => 'Gestão de turmas', 'link' => Config::getData('url') . '/turmas', 'icon' => 'angle-right', 'dropdown' => false],
            //@v2 ['label' => 'Indisponibilidade', 'link' => Config::getData('url') . '/indisp', 'icon' => 'angle-right', 'dropdown' => false],
            ['label' => Config::getData('titlePagesAliases', 'Pessoas'), 'link' => Config::getData('url') . '/Usuario', 'icon' => 'angle-right', 'dropdown' => false],
        ]],
    ['label' => 'Gestão pedagógica', 'link' => '#', 'icon' => 'list', 'dropdown' => [
            ['label' => 'Gerador de grade do polo', 'link' => Config::getData('url') . '/gdf', 'icon' => 'angle-right', 'dropdown' => false],
            ['label' => Config::getData('titlePagesAliases', 'GradePolo'), 'link' => Config::getData('url') . '/GradePolo', 'icon' => 'angle-right', 'dropdown' => false],
            ['label' => 'Indisponibilidade', 'link' => Config::getData('url') . '/indisp', 'icon' => 'angle-right', 'dropdown' => false],
            ['label' => Config::getData('titlePagesAliases', 'Pessoas'), 'link' => Config::getData('url') . '/Usuario', 'icon' => 'angle-right', 'dropdown' => false],
        ]],
    ['label' => 'Área do professor', 'link' => '#', 'icon' => 'pencil', 'dropdown' => [
            ['label' => 'Gestão de turmas', 'link' => Config::getData('url') . '/turmas', 'icon' => 'angle-right', 'dropdown' => false],
            //@v2 ['label' => 'Indisponibilidade', 'link' => Config::getData('url') . '/indisp', 'icon' => 'angle-right', 'dropdown' => false],
            ['label' => Config::getData('titlePagesAliases', 'Pessoas'), 'link' => Config::getData('url') . '/Usuario', 'icon' => 'angle-right', 'dropdown' => false],
        ]],
        /*
          ['label' => 'Todos', 'link' => '#', 'icon' => 'angle-right', 'dropdown' => [
          ['label' => 'Grade full', 'link' => Config::getData('url') . '/gdf', 'icon' => 'angle-right', 'dropdown' => false],
          ['label' => 'Indisponibilidade', 'link' => Config::getData('url') . '/indisp', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'App'), 'link' => Config::getData('url') . '/App', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'ApiLog'), 'link' => Config::getData('url') . '/ApiLog', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'Auxiliar'), 'link' => Config::getData('url') . '/Auxiliar', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'Cep'), 'link' => Config::getData('url') . '/Cep', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'Empresa'), 'link' => Config::getData('url') . '/Empresa', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'Endereco'), 'link' => Config::getData('url') . '/Endereco', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'Linktable'), 'link' => Config::getData('url') . '/Linktable', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'LoginAttempts'), 'link' => Config::getData('url') . '/LoginAttempts', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'LtRel'), 'link' => Config::getData('url') . '/LtRel', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'Mensagem'), 'link' => Config::getData('url') . '/Mensagem', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'MensagemGrupo'), 'link' => Config::getData('url') . '/MensagemGrupo', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'MensagemGrupoUsers'), 'link' => Config::getData('url') . '/MensagemGrupoUsers', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'Municipio'), 'link' => Config::getData('url') . '/Municipio', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'Pais'), 'link' => Config::getData('url') . '/Pais', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'Post'), 'link' => Config::getData('url') . '/Post', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'PostRead'), 'link' => Config::getData('url') . '/PostRead', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'Shared'), 'link' => Config::getData('url') . '/Shared', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'SharedUser'), 'link' => Config::getData('url') . '/SharedUser', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'SistemaFuncao'), 'link' => Config::getData('url') . '/SistemaFuncao', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'SistemaLog'), 'link' => Config::getData('url') . '/SistemaLog', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'Status'), 'link' => Config::getData('url') . '/Status', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'Trash'), 'link' => Config::getData('url') . '/Trash', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'Uf'), 'link' => Config::getData('url') . '/Uf', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'Uploadfile'), 'link' => Config::getData('url') . '/Uploadfile', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'Usuario'), 'link' => Config::getData('url') . '/Usuario', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'UsuarioPermissao'), 'link' => Config::getData('url') . '/UsuarioPermissao', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'Avaliacao'), 'link' => Config::getData('url') . '/Avaliacao', 'icon' => 'angle-right', 'dropdown' => false],
          ['label' => Config::getData('titlePagesAliases', 'Bolsa'), 'link' => Config::getData('url') . '/Bolsa', 'icon' => 'angle-right', 'dropdown' => false],
          ['label' => Config::getData('titlePagesAliases', 'Curso'), 'link' => Config::getData('url') . '/Curso', 'icon' => 'angle-right', 'dropdown' => false],
          ['label' => Config::getData('titlePagesAliases', 'Financeiro'), 'link' => Config::getData('url') . '/Financeiro', 'icon' => 'angle-right', 'dropdown' => false],
          ['label' => Config::getData('titlePagesAliases', 'Forum'), 'link' => Config::getData('url') . '/Forum', 'icon' => 'angle-right', 'dropdown' => false],
          ['label' => Config::getData('titlePagesAliases', 'Grade'), 'link' => Config::getData('url') . '/Grade', 'icon' => 'angle-right', 'dropdown' => false],
          ['label' => Config::getData('titlePagesAliases', 'GradeAluno'), 'link' => Config::getData('url') . '/GradeAluno', 'icon' => 'angle-right', 'dropdown' => false],
          ['label' => Config::getData('titlePagesAliases', 'GradePolo'), 'link' => Config::getData('url') . '/GradePolo', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'Leciona'), 'link' => Config::getData('url') . '/Leciona', 'icon' => 'angle-right', 'dropdown' => false],
          ['label' => Config::getData('titlePagesAliases', 'Matricula'), 'link' => Config::getData('url') . '/Matricula', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'Modulo'), 'link' => Config::getData('url') . '/Modulo', 'icon' => 'angle-right', 'dropdown' => false],
          //            ['label' => Config::getData('titlePagesAliases', 'Polo'), 'link' => Config::getData('url') . '/Polo', 'icon' => 'angle-right', 'dropdown' => false],
          ['label' => Config::getData('titlePagesAliases', 'Reembolso'), 'link' => Config::getData('url') . '/Reembolso', 'icon' => 'angle-right', 'dropdown' => false],
          ['label' => Config::getData('titlePagesAliases', 'ReembolsoMotivo'), 'link' => Config::getData('url') . '/ReembolsoMotivo', 'icon' => 'angle-right', 'dropdown' => false],
          ['label' => Config::getData('titlePagesAliases', 'SolicitacaoCompra'), 'link' => Config::getData('url') . '/SolicitacaoCompra', 'icon' => 'angle-right', 'dropdown' => false]
          ]]
         */
];
